name: Test Build LuCI Package Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - action.yml
      - .github/workflows/test-action.yml

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg_type: [ipk, apk]
    steps:
      - name: Checkout action repo
        uses: actions/checkout@v6

      - name: Checkout luci-theme-aurora
        uses: actions/checkout@v6
        with:
          repository: eamonxg/luci-theme-aurora
          path: package
          fetch-depth: 0

      - name: Build luci-theme-aurora (${{ matrix.pkg_type }})
        uses: ./
        with:
          package: luci-theme-aurora
          pkg_type: ${{ matrix.pkg_type }}
          source_dir: package
          skip_checkout: "true"
          prep_script: |
            ./scripts/feeds update -f base luci
            ./scripts/feeds install -p luci-base
          artifact_paths: |
            bin/packages/$ARCH/base/*luci-theme-aurora*.[ai]pk
          release_body_repo: eamonxg/assets
          release_body_path: aurora/docs/theme/changelog/${{ github.ref_name }}.md
